name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Arguments'
        required: true
        default: '--publish'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - run: dotnet run --project "build/RhinoPackager.Build/RhinoPackager.Build.csproj" -- ${{ github.event.inputs.arguments || '--publish' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
